dubbo:
  application:
    name: boot-user-service-provider
  registry:
    address: zookeeper://47.104.80.23:2181
  protocol:
    name: dubbo
    port: 20880
  monitor:
    address: dubbo://47.104.80.23:7070
  scan:
    base-packages: com.provider.service.impl
server:
  port: 8090